version: '3'

services:
  postgres-vacaciones:
    image: postgres:latest
    container_name: postgres-vacaciones
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_DB: vacaciones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  backend:
    build:
       context: ./vacaciones
       dockerfile: Dockerfile
    container_name: backend
    command: java -jar app.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-vacaciones:5432/vacaciones
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on: 
      - postgres-vacaciones